### ISSUE TITLE
[Proposal]: Add Sentry for Realtime Analytics

### ISSUE THREAD

**Issue by dukesx** [dukesx/Coding-Bolt#140]
#### What & Where
Sentry has been out there for quite a while and used by Fortune-500 companies to ensure quick error catching, patching and deployment. This issue addresses the proposal mentioned in #139  where the spec has been drafted and will soon be merged

#### Future
- [x] Add Initial Config
- [x] Test "Throw" error on analytics dashboard
- [x] Check Realtime Dev Stats
- [ ] Integrate with Next js route/api
- [x] Ensure RFC compliance
- [x] Integrate with SemVer Release
