### ISSUE TITLE
[Proposal] Migrate from Firebase Auth to Next Auth

### ISSUE THREAD

**Issue by dukesx** [dukesx/Coding-Bolt#148]
### Proposal Brief
Firebase Auth is very dynamic and versatile in it's approach but what it is not, is web optimized and specifically optimized for Next.js which makes "approach" lackluster in implementation, documentation and practicality. Initially firebase was chosen to mitigate complexities in managing oAuth on Flutter Application but since Flutter-Web-Auth, this may change and allow easier authentications.

#### Plan of Execution
As of now, this stands as a draft and will now opt for a new branch to start working on the implementation, which will hopefully give rise to lesser bundle size and faster, easier and familiar web auth experience. At a later stage, Google YOLO (One tap) will also be included, once RFC has been finalized with finalized base features

- [x] Create branch
- [x] Install Next Auth
- [ ] Implement SSR
- [x] Implement Client Side
- [ ] Check Web Working
    - [ ]  Production
    - [x] Development
- [ ] Check on Flutter
